backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "Posts"
    label: "Posts"
    folder: "src/pages/posts"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: description, label: Description, widget: string}
      - { name: tags, label: Tags, widget: list, required: true}
      - { name: author, label: Author, widget: list, default: YOUR--WEBSITE--NAME}
      - { name: draft, label: Draft, widget: boolean, default: false}
      - { name: body, label: Body, widget: markdown }
