backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "Posts"
    label: "Posts"
    folder: "src/pages/posts"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: description, label: Description}
      - { name: body, label: Body, widget: markdown }
